name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask Jinja2 Werkzeug click pymongo pytest

    - name: Wait for MongoDB
      run: |
        until mongo --eval 'db.runCommand({ ping: 1 })'; do
          echo "Waiting for MongoDB to be ready..."
          sleep 2
        done

    - name: Run Tests
      run: |
        pytest -v
